spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.group.xlibris: DEBUG

xlibris:
  validator:
    enabled: true
    title: "Validation failed"
    detail: "Request contains invalid fields"